version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    container_name: DB
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=NMCNPM_2022
    ports:
      - 27017:27017 # Should not exposed on production server
    volumes:
      - ./entrypoint:/docker-entrypoint-initdb.d
      - mongodb_data_container:/data/db
  webapp:
    image: "node:alpine"
    user: "root"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development 
                #production
      - PORT=20222
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=NMCNPM_2022
    volumes:
      - ./webapp:/home/node/app
      - node_modules_container:/home/node/app/node_modules
    ports:
      - 20222:20222
      - 9229:9229 # Debug port, Should not exposed on production server
    command: ash -c "npm install --save&&npm start"
    depends_on: 
      - mongodb_container
      - image_microservice
  image_microservice:
    image: "python:3-alpine"
    user: "root"
    working_dir: /home/abc/app 
    ports:
      - 1234:2234 # Should not exposed on production server
    volumes:
      - ./image-microservice:/home/abc/app
    command: ash -c "pip install --no-cache-dir -r ./requirements.txt && python3 ./main.py"


volumes:
  mongodb_data_container:
  node_modules_container:
